### ISSUE TITLE
US32 Páginas de pedidos em andamento e histórico

### ISSUE THREAD

**Issue by alanrslima** [fga-desenho-2019-2/Wiki#103]
## Descrição da Issue
Eu, como cliente, gostaria de visualizar meus pedidos em andamento para acompanhar o preparo e comer quando estiver pronto, e o histórico de pedidos para saber os locais que eu pedi comida.

### Critérios de aceitação:

* Deverá ter uma página para histórico de pedidos
* Deverá ter uma página para acompanhamento de pedidos
* Deverá ter um modal com a senha e informações do pedido em andamento
* Deverá ter uma um modal com informações e avaliação para pedidos já concluídos
* Adicionar um campo de observação no serviço de pedidos
* Deverá estar integrado com o back-end
* Funcionalidade testada;

### Tasks:

- [x] Criar tela de histórico e acompanhamento de pedidos
- [x] Criar modal para informações de cada pedido
- [x] Criar link com a pagina do restaurante do pedido 
- [x] Adicionar campo de observação no serviço de pedidos
- [x] Integrar com o backend

**Comment by MatheusBlanco** [comment]
front quase pronto, back tá quaase pronto, mas não tanto quanto o back
