### ISSUE TITLE
Salvar imagens no back-end

### ISSUE THREAD

**Issue by silvasara** [fga-desenho-2019-2/Wiki#104]
## Nome da Issue
Salvar imagens no back-end

## Descrição da Issue
Salvar imagens de restaurante, item e usuário no back-end de cada serviço

### Tasks:
- [x] Salvar imagem de restaurante no restarurant-service
- [x] Salvar imagem de item no restaurant-service
- [x] Salvar imagem de usuário no user-service

**Comment by silvasara** [comment]
PRs abertos para review, no restaurant-service e no user-service
