### ISSUE TITLE
Api aberta de restaurante

### ISSUE THREAD

**Issue by silvasara** [fga-desenho-2019-2/Wiki#105]
## Nome da Issue
Api aberta de restaurante

### Tasks:
- [x] Endpoints para integração com outros sistemas
- [ ] Documentação da api
- [x] Receber pedido
- [x] Atualizar status do pedido
