### ISSUE TITLE
Documento de arquitetura & atualizar wiki

### ISSUE THREAD

**Issue by ebmm01** [fga-desenho-2019-2/Wiki#110]
## Descrição da Issue
Definir e escrever na wiki o documento de arquitetura e atualizar a wiki

### Tasks:
- [x] Criar documento de arquitetura
- [ ] Atualizar a dinâmica sobre padrões de projetos para refletir o código atual
- [x] Atualizar eventuais documentos e artefatos desatualizados
