### ISSUE TITLE
Protótipo de alta fidelidade

### ISSUE THREAD

**Issue by Phe0** [fga-desenho-2019-2/Wiki#24]
## Nome da Issue
Protótipo de alta fidelidade

## Descrição da Issue
Desenvolver protótipo de alta fidelidade da aplicação
### Tasks:
- [x] Construir protótipo para o cliente dos restaurantes
- [ ] Construir protótipo para o dono do restaurante
- [x] Validar com o time

**Comment by alanrslima** [comment]
O protótipo esta sendo desenvolvido no link a seguir: [https://www.figma.com/file/unhRDokaYlRCUGswOKZ6Jo/Untitled?node-id=0%3A1](https://www.figma.com/file/unhRDokaYlRCUGswOKZ6Jo/Untitled?node-id=0%3A1)
