### ISSUE TITLE
Criar modelo de dados

### ISSUE THREAD

**Issue by alanrslima** [fga-desenho-2019-2/Wiki#26]
## Nome da Issue
[Descrição simples da tarefa a ser realizada.]
Criar um projeto de banco de dados que contemple o fluxo da aplicação.

## Descrição da Issue
[Descrever issue brevemente, colocando informações necessárias para a realização da mesma.]
Desenvolver um projeto de dados.

### Tasks:
- [x] Criar modelo conceitual de dados
- [x] Criar modelo relacional de dados
- [x] Criar dicionário de dados

**Comment by alanrslima** [comment]
O arquivo em que está sendo feito o modelo de dados está disponível [AQUI](https://drive.google.com/file/d/1nGjofTVUt7FX_DN62UGTZRHjXCeeW_Cx/view?usp=sharing). Obs: É necessário possuir o software [BRMODELO](https://sourceforge.net/projects/brmodelo30/)

**Comment by pedro-prp** [comment]
To dando uma revisada, acredito que não precisa de uma entidade ENDERECO, já que não vai ter mais de um shopping numa mesma localização, então poderia estar como atributos de SHOPPING.

**Comment by pedro-prp** [comment]
Ai galera, dei uma mexida grande no modelo de dados.
Link do novo arquivo: [LINK](https://drive.google.com/open?id=1Hr5M6nqqyKF1K3SRzBNvPzVwVdbU8s2b)

Ainda falta coisa, mas ta indo.

**Comment by leossb36** [comment]
Será feito um modelo para cada microsserviço:
- [x] User
- [x] Restaurante
- [x] Pedido

manter modelo atual como modelo geral

**Comment by leossb36** [comment]
hotfix:
- [ ] Reestruturar documentação
- [ ] Incluir novo modelo de dados

**Comment by shayanealcantara** [comment]
Comecem a trabalhar pela issue #51, porque está redundante. Fechando a issue e fazendo uma cópia do comentário acima.
