### ISSUE TITLE
Analisar e colher dados do brainstorm para a modelagem de requisitos

### ISSUE THREAD

**Issue by shayanealcantara** [fga-desenho-2019-2/Wiki#28]
## Descrição da Issue
Para dar prosseguimento ao processo do projeto proposto, deve-se realizar a modelagem dos requisitos para então, iniciar de fato o desenvolvimento ou algo relacionado, dando direcionamento.

### Tasks:
- [x] Analisar e elicitar requisitos referentes ao brainstorm;
- [x] Documentar os requisitos elicitados;
- [x] Seguir template do arquivo em `Wiki/docs/iniciativas_extras/elicitacao_de_requisitos/req_questionario.md`
