### ISSUE TITLE
Analisar e colher dados dos storytellings para a modelagem de requisitos

### ISSUE THREAD

**Issue by shayanealcantara** [fga-desenho-2019-2/Wiki#32]
## Descrição da Issue
Para dar prosseguimento ao processo do projeto proposto, deve-se realizar a modelagem dos requisitos para então, iniciar de fato o desenvolvimento ou algo relacionado, dando direcionamento.

### Tasks:
- [x] Analisar e elicitar requisitos referentes aos storytellings;
- [x] Documentar os requisitos elicitados;
- [x] Seguir template do arquivo em `Wiki/docs/iniciativas_extras/elicitacao_de_requisitos/req_questionario.md`

### Relacionada à issue: #14

**Comment by devsalula** [comment]
Fiz a análise das Storytelling e escrevi alguns requisitos, @leossb36 se puder dar uma olhada.
