### ISSUE TITLE
Analisar e colher dados do protótipo para a modelagem de requisitos

### ISSUE THREAD

**Issue by shayanealcantara** [fga-desenho-2019-2/Wiki#33]
## Descrição da Issue
Para dar prosseguimento ao processo do projeto proposto, deve-se realizar a modelagem dos requisitos para então, iniciar de fato o desenvolvimento ou algo relacionado, dando direcionamento.

### Tasks:
- [x] Analisar e elicitar requisitos referentes ao protótipo;
- [x] Documentar os requisitos elicitados;
- [x] Seguir template do arquivo em `Wiki/docs/iniciativas_extras/elicitacao_de_requisitos/req_questionario.md`

**Comment by Phe0** [comment]
@leossb36 @alanrslima adicionei os requsitos lá, deem uma olhada e adicionem mais se acharem necessário

**Comment by shayanealcantara** [comment]
Requisitos elicitados e já documentos, de acordo com a issue #34 :sunglasses:
