### ISSUE TITLE
Síntese dos requisitos elicitados

### ISSUE THREAD

**Issue by shayanealcantara** [fga-desenho-2019-2/Wiki#34]
## Descrição da Issue
Realizar a síntese dos requisitos elicitados e reunir os mais viáveis.

### Tasks:
- [x] Realizar a síntese dos requisitos;
- [x] Notificar a equipe para selecionar os requisitos viáveis;
- [x] Documentar para colocar no backlog.

### Relacionada às issue: #28 #29 #30 #31 #32 #33

**Comment by shayanealcantara** [comment]
Será realizada hoje (02/09) no horário do almoço.

**Comment by shayanealcantara** [comment]
**Entrevistas**
E02
E03
E04 e E18
E05
E06 *
E07
E08 *
RNFE10
E11 *
E12 *
E14
E15
E16
E17
E19 *
E20 *
E21

**Questionário**
Q06
Q07
Q09
Q10

**Brainstorm**
BR01
BR06
BR07
BR10
BR11
BR14

**Storytelling**
ST02
ST04
ST05
ST06
ST07 *
ST08 * (reescrever)
ST09
ST10
ST11
ST12
ST13
ST14
ST16
ST19

**BENCHMARKING**
BENCH01
BENCH04 (ajustar texto)
BENCH07 (estática)
BENCH10

**PROTÓTIPO**
PRO01
PRO04
PRO05
PRO06
PRO07
PRO13 (linkar com o de histórico)
PRO17
PRO18
PRO19
PRO20
PRO21
PRO24 *
PRO25
PRO26
PRO27
PRO28
PRO29 (linkar com o suporte)



LEGENDA:
* = Observação a ser discutida

**Comment by shayanealcantara** [comment]
[BRAINSTORM]
BR01 - O Sistema deve diferenciar perfis de cliente e restaurante | Must have
BR06 - O Sistema deve possuir possuir API aberta para integração com outros sistemas | Must have
BR07 - O Sistema deve disponibilizar apenas um QR code por  | Must have
BR10 - O Sistema deve expirar a sessão do cliente após um período de tempo pré definido | Should have
BR11 - O Sistema deve validar as franquias cadastradas por meio do CNPJ | Could have
BR14 - O Sistema deve possuir uma forma de prevenir da desistência de pedidos | Could have

**Comment by pedro-prp** [comment]
[QUESTIONÁRIO]
Q06 - A aplicação deverá apresentar as informações de forma prática | Must have
Q07 - A aplicação deverá apresentar as informações de forma clara e organizada | Must have
Q09 - No fluxo de pedido pela aplicação não deve haver filas para o usuário | Must have
Q10 - No fluxo de pedido pela aplicação o usuário não precisará interagir com atendentes | Must have

**Comment by silvasara** [comment]
[BENCHMARKING]
BENCH01 - O app deve ter uma página de suporte | Should have
BENCH04 (ajustar texto) - A aplicação deve ser a prova de falhas e possuir boa performance | Could have
BENCH07 (estática) - O app deve exibir uma previsão de tempo do pedido | Should have
BENCH10 - O app deve permitir o cancelamento do pedido | Could have

**Comment by devsalula** [comment]
[Protótipo]
PRO25 O usuário deve ser capaz de visualizar seu perfil
PRO26 O usuário deve ser capaz de editar seu perfil
PRO27 O usuário deve ser capaz de visualizar os termos de uso e as políticas de privacidade
PRO28 O usuário deve ser capaz de visualizar seus cartões cadastrados
PRO29 (linkar com o suporte) O usuário deve ser capaz de tirar dúvidas a respeito da aplicação

**Comment by alanrslima** [comment]
[PROTÓTIPO]
PRO04 - O app deve possuir uma página falando sobre a aplicação | Should have
PRO06 - O app deve possuir uma página falando sobre os parceiros que já utilizam o QR Comer | Could have
PRO07 - O app deve conseguir recuperar sua senha caso a esqueça | Must have
PRO13 (linkar com o de histórico) - O app deve apresentar os pedidos em andamento do usuário | 
PRO17 - O usuário deve ser capaz de adicionar um pedido à sacola | Must have
PRO18 - Na sacola o usuário deve ser capaz de editar os itens que estão nela | Must have
PRO19 - A sacola deve apresentar um resumo dos itens que o usuário está pedindo | Must have
PRO20 - A sacola deve permitir que o usuário escolha sua forma de pagamento e adicione CPF | Must have
PRO21 - A sacola deve permitir que o usuário finalize seu pedido | Must have
PRO24 * - O usuário deve ser capaz de avaliar o restaurante onde já fez seu pedido | Could have
PRO25 - O usuário deve ser capaz de visualizar seu perfil | Should have
PRO26 - O usuário deve ser capaz de editar seu perfil | Should have
PRO27 - O usuário deve ser capaz de visualizar os termos de uso e as políticas de privacidade | Would
PRO28 - O usuário deve ser capaz de visualizar seus cartões cadastrados | Must have
PRO29 (linkar com o suporte) - O usuário deve ser capaz de tirar dúvidas a respeito da aplicação | Would have

**Comment by leossb36** [comment]
[STORYTELLING]
ST02 - As mesas dos shoppings devem conter QRCodes | Must have
ST04 - O sistema deve ser Web | Must have
ST05 - O QRCode deve direcionar o usuário para o QRComer | Must have
ST06 - O sistema deve possuir uma área de cadastro do usuário | Must
ST07 * - O sistema deve possuir integração com outras API's de cadastro | Could
ST09 - O sistema deve possuir uma tela de carregamento como feedback para o usuário | Should have
ST10 - O sistema deve informar o shopping onde o usuário está localizado | Must have
ST11 - O sistema deve demonstrar a lista de restaurantes do shopping | Must have
ST12 - O sistema deve permitir a escolha de um restaurante pelo usuário | Must have
ST13 - O sistema deve informar os itens do cardápio do restaurante | Must have
ST14 - O sistema deve permitir que o usuário escolha itens do cardápio do restaurante | Must have
ST19 - O sistema deve gerar uma senha do pedido do usuário | Must have

**Comment by devsalula** [comment]
[Entrevista]
E02 - Fazer pedido a partir da aplicação | Must have
E03 - Acessar a aplicação a partir de um QR Code | Must have
E04 e E18 - Aceitar pagamento por cartão de crédito e Cadastrar cartão de crédito | Must have
E07 - Criptografar os dados de cartão | Should have
E08 * - Possibilitar pagamento por dinheiro no caixa | Would have
RNFE10 - Portabilidade | Could have
E11 * - Autenticação dupla | Would have
E12 * - Acrescentar adicionais | Should have
E14 - Acrescentar observações relativas ao pedido | Should have
E15 - Possuir imagens para descricao dos itens | Should have
E16 - Possuir descricao dos itens | Should have
E17 - Guardar histórico de pedidos | Could have
E19 * - Receber notificação sobre a completude do pedido | Would have
E20 * - Possuir categoria de pratos | Should have
E21 - Cadastrar restaurantes | Must have

**Comment by shayanealcantara** [comment]
Requisitos elicitados no arquivo `/Wiki/docs/iniciativas_extras/elicitacao_de_requisitos/elicitacao_de_requisitos.md` por ordem de priorização
