### ISSUE TITLE
 Documentar e justificar a metodologia

### ISSUE THREAD

**Issue by silvasara** [fga-desenho-2019-2/Wiki#43]
## Descrição da Issue
Documentar e justificar os apectos escolhidos pra metodologia do grupo

### Tasks:
- [x] Pair programming
- [x] Limite de WIP
- [x] Classificação de dificuldade
- [x] Uso de e-Kaban
- [x] Sprint
- [x] Gitflow
- [x] Dailys
- [x] Piplene CI/CD
- [x] Quadro de conhecimento
- [x] PR

**Comment by shayanealcantara** [comment]
@ebmm01 @guilhesme23 Qual é o status desta issue?

**Comment by ebmm01** [comment]
Finalizada.
