### ISSUE TITLE
Criar caso de uso sobre a aplicação 

### ISSUE THREAD

**Issue by shayanealcantara** [fga-desenho-2019-2/Wiki#49]
## Descrição da Issue
Criar caso de uso sobre a aplicação 

### Tasks:
- [x] Criar modelo usando a ferramenta Draw.io
- [x] Documentar o diagrama

**Comment by shayanealcantara** [comment]
Primeira versão já documentada. Aguardando revisão para fechar esta issue.

**Comment by shayanealcantara** [comment]
Pontos de melhoria: 
- [x] Ajustar alguns includes e extends;
- [x] Substituir logo do QR Comer por um módulo específico.

**Comment by shayanealcantara** [comment]
@ebmm01 irá revisar e realizar os devidos ajustes desta issue.
