### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by Phe0** [fga-desenho-2019-2/Wiki#6]
## Nome da Issue
Realizar pesquisa de Benchmarking

## Descrição da Issue
Estudar como apps e soluções similares a nossa ideia resolvem seus problemas, que features apresentam e como é o modelo de mercado de cada um deles.

### Tasks:
- [ ] Listar possíveis soluções similares
- [ ] Fazer pesquisa sobre as soluções
- [ ] Escrever documento falando sobre as informações coletadas

**Comment by Phe0** [comment]
**Onyo**: 
https://play.google.com/store/apps/details?id=com.onyo&hl=pt_BR
https://www.site.onyo.com/en
https://projetodraft.com/onyo-um-app-que-adianta-pedidos-de-restaurantes-em-pracas-de-alimentacao/

**Burguer King**:
https://cupons.burgerking.com.br/
https://play.google.com/store/apps/details?id=burgerking.com.br.appandroid&hl=pt_BR
https://apps.apple.com/br/app/burger-king-brasil/id1295116265

**VoceQPad**:
http://app.voceqpad.com.br/
https://www.facebook.com/voceqpad/
https://play.google.com/store/apps/details?id=br.com.voceqpad.voceqpadsmartphone&hl=pt_BR&showAllReviews=true

**Comment by ebmm01** [comment]
O **Ifood**, por permitir retirar no estabelicimento, também pode ser considerado uma solução similar:

https://www.huffpostbrasil.com/2018/04/18/como-o-ifood-se-tornou-o-maior-aplicativo-de-delivery-de-comida-da-america-latina_a_23414651/
https://www.salesforce.com/br/customer-success-stories/ifood/
