### ISSUE TITLE
Criar backlog do produto

### ISSUE THREAD

**Issue by leossb36** [fga-desenho-2019-2/Wiki#66]
## Nome da Issue
Criar backlog do produto

## Descrição da Issue
definir o escopo do backlog

### Tasks:
- [ ] Elaborar template backlog
- [ ] Elaborar sprints backlog
- [ ] Elaborar historias de usuarios
