### ISSUE TITLE
US06 - [Front-end] Landing page QRComer

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-desenho-2019-2/Wiki#70]
## Descrição
Eu, como cliente, gostaria de abrir a aplicação e me deparar com uma página inicial tanto em desktop quanto mobile, para que eu possa saber mais sobre o intuito da aplicação e para que eu possa acessar outras funcionalidades.

## Critérios de aceitação
- [ ] Deverá conter um texto explicativo;
- [ ] Deverá conter a logo da aplicação;
- [ ] Deverá conter a identidade visual do protótipo;
- [ ] Deverá ser responsivo;

### Tasks:
- [ ] Criar landing page com VueJS;
- [ ] Adicionar logo do projeto;
- [ ] Adicionar SVG tirado do protótipo;
- [ ] Adicionar texto explicativo do projeto;
- [ ] Tornar responsivo para utilização também em mobile;

**Comment by shayanealcantara** [comment]
PR desta issue já foi aceito. Por isso estou fechando a issue. @ebmm01 @devsalula não esqueçam de atuallzar o kanban e o checklist da descrição da issue
