### ISSUE TITLE
Rich Pictures

### ISSUE THREAD

**Issue by Phe0** [fga-desenho-2019-2/Wiki#8]
## Nome da Issue
Rich Pictures

## Descrição da Issue
Elaborar rich pictures para facilitar o entendimento da aplicação por meio de diferentes pontos de vista. Ex.: Usuário, Shopping, Restaurante

### Tasks:
- [ ] Desenhar Rich Picture
- [ ] Comentar na issue
- [ ] Se necessário fazer segunda versão com identidade visual

**Comment by Phe0** [comment]
![photo5102918264798947382](https://user-images.githubusercontent.com/31973465/63270947-7a44d300-c26f-11e9-90ca-051b44378920.jpg)

**Comment by pedro-prp** [comment]
Vou fazer um geral sobre pedido usando cartão de crédito.

**Comment by silvasara** [comment]
Vou fazer um sobre como a aplicação atende as necessidades/preocupações do usuário e seu incomodo com as filas.

**Comment by guilhesme23** [comment]
Vou fazer um sobre o restaurante atendendo os pedidos

**Comment by ebmm01** [comment]
Vou fazer um sobre a utilização do celular para o pedido vs atendimento no caixa (do ponto de vista usuário)

**Comment by shayanealcantara** [comment]
Vou fazer um sobre a segurança básica do sistema.

**Comment by Phe0** [comment]
vou fazer um bem geral sobre a visão do restaurante
