### ISSUE TITLE
[Back-end] Mock Pagamento

### ISSUE THREAD

**Issue by guilhesme23** [fga-desenho-2019-2/Wiki#93]
## Nome da Issue
Mock do serviço de pagamentos

## Descrição da Issue
Definir a lógica do mock, procurando aplicar os padrões onde for possível ser aplicado.
O serviço deve consumir os dados como cartão de credito, pedidos do usuário, receber parâmetros para definir se a transação será um sucesso ou não.
O resultado da transação deve atualizar o estado do pedido e notificar o restaurante responsável.

### Tasks:
- [ ] Criar as views responsáveis por receber os dados de pagamento
- [ ] Criar a lógica para notificar o restaurante do pedido
- [ ] Criar lógica para alterar o status de um pedido para: "pago"

### Critérios de aceitação
- [ ] Código testado
